#!/usr/bin/env bash
set -euo pipefail

# let cp find zshrc / p10k.zsh from any directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

### 1. system packages ###
apt update
apt install -y zsh tmux vim git curl

### 2. oh-my-zsh -- critical: --unattended to prevent it from exec zsh / chsh ###
export RUNZSH=no CHSH=no KEEP_ZSHRC=yes
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

### 3. plugins & themes (skip if already exists to avoid errors on re-run)###
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "$ZSH_CUSTOM/plugins/zsh-syntax-highlighting" 2>/dev/null || true
git clone https://github.com/zsh-users/zsh-autosuggestions     "$ZSH_CUSTOM/plugins/zsh-autosuggestions"     2>/dev/null || true
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$HOME/powerlevel10k"                       2>/dev/null || true

### 4. Claude Code ###
curl -fsSL https://claude.ai/install.sh | bash

### 5. config files (cp will overwrite .zshrc generated by oh-my-zsh, so put it after)###
cp "$SCRIPT_DIR/zshrc"    "$HOME/.zshrc"
cp "$SCRIPT_DIR/p10k.zsh" "$HOME/.p10k.zsh"
echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.zshrc
echo 'set -g default-shell /usr/bin/zsh'    >> ~/.tmux.conf
echo 'set -g default-command /usr/bin/zsh'  >> ~/.tmux.conf

### 6. default shell (chsh occasionally fails in container, add || true to prevent it from interrupting)###
chsh -s "$(which zsh)" || true
echo "=== all done, run exec zsh or restart terminal to enter zsh ==="