#### System configuration ####

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="nord-extended/nord"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true" # COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#### User configuration ####

# export LANG=en_US.UTF-8
export CLICOLOR=1
export TERM=xterm-256color
export XDG_CONFIG_HOME=/Users/purkialo/.config

alias vi='nvim'
alias l='ls -hGall'
alias ll='ls -hGlgo' # --ignore "__pycache__"
alias python="python3"
alias proxy="export ALL_PROXY=socks5://127.0.0.1:7890"
alias watchgpu="watch -n 1 --color gpustat --force-color"

