#### System configuration ####

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# ZSH_THEME="powerlevel10k/powerlevel10k"
# DISABLE_AUTO_TITLE="true"
# ENABLE_CORRECTION="true"
# COMPLETION_WAITING_DOTS="true" # COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# DISABLE_UNTRACKED_FILES_DIRTY="true"

plugins=(
    git
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
source $ZSH/custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

#### User configuration ####

# export LANG=en_US.UTF-8
export CLICOLOR=1
export TERM=xterm-256color
# export XDG_CONFIG_HOME="/home/mil/x-chu/workspace:$PATH"

# alias vi='nvim'
alias l='ls -hGlgo --ignore "__pycache__"'
alias ll='ls -hGlgo --ignore "__pycache__"'
alias python="python3"
alias watchgpu="watch -n 1 --color gpustat --force-color"
